# Exported from Render on 2024-07-17T10:15:03Z
databases:
- name: postgresql-multilang-site
  databaseName: dbmultilangsite
  user: dbmultilangsite_user
  plan: free
  region: frankfurt
  ipAllowList:
    source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
