# Generated by Django 4.2.13 on 2024-06-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_de_blog',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='articles_de_blog',
            name='publication_date',
            field=models.DateTimeField(verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='articles_de_blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
